development:
  host: localhost
  database: drh_wepoll_development

test:
  host: localhost
  database: wepoll_test

# set these environment variables on your prod server
production:
  host: 211.43.193.132
#  port: 27018
#  username: wepoll
#  password: dnlvhf1234
  database: wepoll
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
