source 'https://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# twitter gem
gem 'twitter'

gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
#gem 'omniauth-twitter'
gem 'oauth2'

gem 'thin'

gem 'mongoid'
gem 'bson_ext'

gem 'rspec'

gem 'kaminari'
gem 'nokogiri'


#bootstrap for scaffolding
gem 'twitter-bootstrap-rails', :group => :assets
#gem 'twitter-bootstrap-rails', :git => "git://github.com/seyhunak/twitter-bootstrap-rails.git", :branch => "static"
#
gem "less"

# for file attachment
gem 'mongoid-paperclip', :require => "mongoid_paperclip"
gem 'stalker'

gem 'fastercsv'

gem 'koala'

#group :development do
#  gem 'linecache19', '0.5.13'
#  gem 'ruby-debug-base19', '0.11.26'
#  gem 'ruby-debug19', :require => 'ruby-debug'
#end
